"""Added train model to trains

Revision ID: e1904b65682e
Revises: 
Create Date: 2025-06-06 21:23:46.020948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1904b65682e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.add_column(sa.Column('train_model', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.drop_column('train_model')

    # ### end Alembic commands ###
